### ISSUE TITLE
Now this is interesting. Are you on discord?

### ISSUE THREAD

**Issue by Drillgon200** [MartinTheDragon/Nuclear-Tech-Mod-Remake#1]
In kotlin no less. One day I'll get around to learning that. What made you use kotlin rather than the original java by the way?

**Comment by MartinTheDragon** [comment]
Oh, sorry. This project is kind of dead, but I will be picking it up again some time soon. I currently do not have the time for it and I am planning to be updating this for the Minecraft 1.16 version anyway, so got to wait for Forge too. Now, I am using Kotlin because of its great features like type casting and null safety and some other stuff too. In general, Kotlin is more "bug safe" than Java as it sometimes enforces you to do certain things in a certain way. So some things in Java would compile but fail at runtime where Kotlin crashes at compile time. That way you directly know you have done something wrong without having to let some bad code sit in your code until someone sends you a bug report. Also Kotlin code can be written in less lines than in Java, and I like its code style, but that is a personal preference. About Discord, I am not that of a chatty person and I usually only chat with people I personally know, so I would not be in the mood for that. But if you have any further questions, I will probably answer them.

**Comment by Drillgon200** [comment]
Huh, neato. The bobcat (hbm) posted a link to this in discord, that's why I asked about it. I'm doing the 1.12.2 port for the mod by the way, might be less work to update some of the code from that version rather than 1.7.10, if you plan on continuing this project.
