### ISSUE TITLE
<Bug> The siren don't work on servers

### ISSUE THREAD

**Issue by Al3ssan6r0** [MartinTheDragon/Nuclear-Tech-Mod-Remake#10]
**Describe the bug**
The siren don't work in servers. While in LAN worlds only the host hear the siren.

**To Reproduce**
1. Open a LAN world or join a server that have HBM installed (I tried both in a LAN world hosted by my friend and in a private server hosted by me)
2. Place the Siren
3. Put the track inside
4. Power it with Redstone
5. See bug

**Expected behavior**
The sound track should play itself

**Screenshots**
Not a visible bug

**Software and mod environment info:**
 - Mod Version: 0.0.12.1
 - Other mods installed: 
![image](https://user-images.githubusercontent.com/102186855/169098060-e5d116d4-3c8a-45e9-a3c5-22f3f3b0ce95.png)
 - Forge version: 40.1.19
 
**Additional context**
_Nothing_

**Comment by MartinTheDragon** [comment]
Confirmed, attempting to use the siren on a server produces an exception caused by the following error:
```
java.lang.NoClassDefFoundError: net/minecraft/client/resources/sounds/SimpleSoundInstance
```
This is due to the `SoundInstance` file not being available on the server, and even if it were, as you pointed out, only the host would hear the sound.

The reason this does not happen with the Assembler is that it uses a new sound manager introduced for it, which handles machine sounds client-side. To fix the Siren, it will be ported to that new system as well.

Thanks a lot for reporting!
