### ISSUE TITLE
game crashed when i dropped schrabidium crystal

### ISSUE THREAD

**Issue by koap1** [MartinTheDragon/Nuclear-Tech-Mod-Remake#11]
**Describe the bug**
game crashed when i dropped schrabidium crystal

**To Reproduce**
1. put schrabidium crystal in inventory
2. drop it to the ground
3. game crashed

**Software and mod environment info*
 - Mod Version: latest
 - Forge version: latest 1.18.2 forge version
[crash-2022-08-12_23.20.03-server.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/9329662/crash-2022-08-12_23.20.03-server.txt)

**Comment by MartinTheDragon** [comment]
Hello there, thanks for reporting!

This crash seems to happen due to a core mod modifying some Minecraft code that is responsible for getting entities in a certain area. I have been able to reproduce this issue once with all mods added that you were using, happening only after throwing the crystals around several times. I haven't been able to exactly pin down which mod may cause that issue, but I am quite confident that it isn't NTM, for one because the lines the crash report mentions don't appear to be at the same position as in vanilla, and also because I couldn't reproduce the issue with NTM alone. In case you do manage to reproduce it just with NTM, please let me know, and also if you can manage to find out which mod could be responsible.

I would also like more details on how and when the crash happens, since I had to throw the crystals multiple times for it to happen.

Thanks and have fun!

P.S.: Don't specify that you are using the "latest" version, always specify the actual version number. There were several occasions where someone thought they were using the latest versions when in fact they weren't.

**Comment by koap1** [comment]
i tried some of the mods one by one, and when i entered the world with crystals on the ground using this mod: https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master , the game just instantly froze and i manualy closed the game, but when i entered again droping crystals around for about 1 minute nothing happened, i am not sure if this mod causes the crash
