### ISSUE TITLE
Chemical plant, Assembler, and Press item deletion.

### ISSUE THREAD

**Issue by KauaiMoho** [MartinTheDragon/Nuclear-Tech-Mod-Remake#18]
### Issue description

Issue: A multiblock that is opened then quickly broken will retain its gui. While it cannot be used to process recipes or create an infinite output, any items placed in this "ghost" gui will disappear and be deleted  once the gui has been exited. Relogging did not bring any items back. Tested in creative, in theory should be reproducible in survival with an instamine pick.

Expected behavior: This ghost gui should automatically close itself out upon the server registering the multiblock is broken. If this is not possible, items should drop out when the gui is closed.

### Steps to reproduce

1. Place a assembler/chemplant/press down.
2. Quickly press rmb, then lmb. This will break the multiblock and open the gui.
3. Place any item into the gui slots.
4. Exit the gui.

### Forge version

40.1.76

### Nuclear Tech version

0.0.16

### Other mods

Public Test

**Comment by MartinTheDragon** [comment]
Confirmed, this issue happens due to improper implementations of `AbstractContainerMenu#stillValid`, which is responsible for checking whether the GUI should still be open. An easier way to reproduce this issue is destroying the machines by other means, for example TNT.

Most blocks were affected by this, but not all.

Affected blocks:
- Assembler
- Blast Furnace
- Chemical Plant
- Combustion Generator
- Electric Furnace
- Fat Man
- Launch Pad
- Little Boy
- Press

Thanks for reporting!
