### ISSUE TITLE
HBM Port

### ISSUE THREAD

**Issue by idaghan** [MartinTheDragon/Nuclear-Tech-Mod-Remake#3]
Hi MartinTheDragon. I know you are hardworking but can i want some? Can you port HBM's Nuclear Tech Mod to 1.18. If you port it to 1.18, you have my love. Pls, i believe you. <3

**Comment by MartinTheDragon** [comment]
Hi!
Due to the feedback from several people, including The Bobcat himself, I will be porting the mod to Minecraft 1.18 for its world generation. Work on that started as soon as Forge for 1.18 came out, and will be uploaded on GitHub when a few things that are left are finished.
So yes, NTM for 1.18 confirmed.
The current 1.16.5 port is likely to be discontinued, unless I change my mind, or someone *crazy* is willing to work on that.
(Note: No matter how much you like a mod developer, do not try asking for a port to a newer version, please! This typically results in things ranging from disgust to inducing mental health issues, believe me.)
Thank you for your interest!

**Comment by idaghan** [comment]
Thanks a lot. I will abide by your note.

MartinTheDragon ***@***.***>, 10 Ara 2021 Cum, 09:03
tarihinde şunu yazdı:
