### ISSUE TITLE
unloading and reloading chunks causes missiles already on launchpads to not render

### ISSUE THREAD

**Issue by euanPC** [MartinTheDragon/Nuclear-Tech-Mod-Remake#30]
### Issue description

when re entering an area with a missile on a launchpad the launchpad will render without the missile the missile is still present and will immediatelly appear if you remove it and replace it

### Steps to reproduce

1 put a missile in a launchpad
2 leave the area (unload chunks)
3 re-enter the area

### Forge version

40.1.87

### Nuclear Tech version

0.0.18

### Other mods

![image](https://user-images.githubusercontent.com/40900940/211404436-154c3c4c-93ca-40da-8e05-1bd00a018aca.png)
![image](https://user-images.githubusercontent.com/40900940/211404516-244624de-ec55-4c1e-9ffa-09fe3690e75b.png)

**Comment by MartinTheDragon** [comment]
Hi!
This particular case seems to have been introduced with commit 387624b0, and the culprit affects a few other machines, although not quite as obvious. Caused by me swapping two functions in `SyncedBlockEntity` with each other so it doesn't actually load any initial data, whoops... (I actually saw them multiple times and always thought "Hm, that's a bit weird", bruh)
Thanks for reporting!
