### ISSUE TITLE
[request] can I put this mod on curseforge

### ISSUE THREAD

**Issue by githubuser98k** [MartinTheDragon/Nuclear-Tech-Mod-Remake#4]
as the title 
 can I put this mod on curseforge, I will give every income from mod to you

**Comment by MartinTheDragon** [comment]
As long as you comply with the GNU GPLv3 license.
But if you want me to be happy, ***do not put it on CurseForge***.
This is likely to create some issues, and why would you want to do that anyway?

1. The license was meant for giving freedom for open source software, so it can improve as good as it can by collaboration, but in your case, you would be abusing that a bit in my opinion.
2. The version on CurseForge will constantly be out of date because of their slow approval rate.
3. Why?

If you really want to, go ahead, read the license, follow it **exactly**, compile the project (if you can even do that), and put it on CurseForge. But keep in mind one thing: I will not like it.

Have a nice day!

P.S.: Please do not use GitHub Issues for questions like these, as this is not a feature request. Prefer Discord, or if you do not want to, at least make a blank issue.
