### ISSUE TITLE
Inventory Texture and Rediations on Cats

### ISSUE THREAD

**Issue by Al3ssan6r0** [MartinTheDragon/Nuclear-Tech-Mod-Remake#5]
Hi, MartinTheDragon

I tried this HBM mod remake and I found two bugs (or maybe it is in this way by design... just wanted to contribute):
1) Cats aren't affected by radiations (even Zombie and Skeletons but I thing that is normal).
2) Raw Asbestos doesn't show an inventory texture.

This is the mod list:
 [1.18.1]+SecurityCraft+v1.9.0.2-beta1
AkashicTome-1.5-17
Aquaculture-1.18.1-2.3.3
artifacts-1.18.1-4.0.2
AutoRegLib-1.7-52
balm-2.4.2+0
bedspreads-forge-1.18.1-5.1.0.5
BiomesOPlenty-1.18.1-15.0.0.104-universal (1)
BlockArmor-1.18.1-2.6.9
Botania-1.18.1-429
cc-tweaked-1.18.1-1.100.2
ChiselsBits-forge-1.18.1-1.2.77-universal (1)
comforts-forge-1.18.1-5.0.0.2
configured-1.5.1-1.18.1
CraftTweaker-forge-1.18.1-9.0.45
createaddition-1.18.1-20220125a
create-mc1.18.1_v0.4d (1)
curios-forge-1.18.1-5.0.6.0 (1)
Decorative+Blocks-forge-1.18.1-2.0.4 (1)
enhancedcelestials-2.0.9-1.18
expandability-5.0.0-forge
ExplorersCompass-1.18.1-2.0.2-fabric
flywheel-forge-1.18-0.6.0 (1)
furniture-7.0.0-pre28-1.18.1
gemsnjewels-1.18.1-0.2.9
hardcorerevival-forge-1.18-8.0.0
ImmersiveEngineering-1.18.1-7.1.0-145
 jei-1.18.1-9.2.1.69
JustEnoughResources-1.18.1-0.13.1.138
Mantle-1.18.1-1.8.31
MineTraps-1.18-(v.2.0.0)
NaturesCompass-1.18.1-1.9.4-forge
nucleartech-1.18.1-0.0.11.0
OptiFine_1.18.1_HD_U_H4
Patchouli-1.18.1-65
PatinaPipeworks-1.18.1-1.0.6-universal
polymorph-forge-1.18.1-0.37
Quark-3.0-334 (1)
QuarkOddities-1.18 (1)
secretrooms-1.18.1-1.1.4
selene-1.18-1.12.0
SereneSeasons-1.18.1-6.0.0.10-universal
soultrap-1.18.1-1.0.0
subpocket-1.18-8.0.1.0
supplementaries-1.18.1-1.1.11 (1)
swingthroughgrass-1.18.1-1.8.0
TConstruct-1.18.1-3.4.1.46
TerraBlender-forge-1.18.1-1.1.0.73
ToughAsNails-1.18.1-6.0.0.67-universal
Trapcraft-1.18.1-3.6.4
trapperpelts-1.0.1
TravelersBackpack-1.18.1-7.0.1 (1)
worldedit-mod-7.2.9

I didn't find till now any other bug and I really think that your remake is awesome!

Al3ssan6r0
![bug report image 1](https://user-images.githubusercontent.com/102186855/159572483-e402b424-cc71-4675-89dd-6645005d1512.png)
![bug report image 2](https://user-images.githubusercontent.com/102186855/159572489-1124a28c-0c49-4cae-a23c-40825c63280f.png)

**Comment by MartinTheDragon** [comment]
Hi there!

Cats are immune to all radiation in 1.7.10 (as of recent also Digamma), because we cannot handle killing these cuties. <3
So the port also follows this, along with them being immune to nuclear explosions.

The reasons for the raw asbestos texture being absent are:
- Asbestos is planned on being redesigned generation-wise, probably similar to how tuff generates, as well as how processing it works.
- A very kind man of the nickname Pheo volunteered to create these textures for me (ores and raw ores), but left asbestos out. In this case it doesn't matter because of the aforementioned reason.

While everything is actually working as intended, I still really appreciate you taking your time to create a detailed report!
And I had no idea people were already throwing in this port together with other mods in a modpack, since a lot of features are still missing and there is only little progression implemented, but it's still nice to see! (just expect things to break when updating lol)

Thanks!
