### ISSUE TITLE
nuclear reactor bug effect to chunk loader

### ISSUE THREAD

**Issue by Duckng2003** [MartinTheDragon/Nuclear-Tech-Mod-Remake#54]
### Issue description

when i go to the setting to change chunk distance near the nuclear reactor the fps drop to 1

### Forge version

40.2.0

### Nuclear Tech version

0.0.20

**Comment by MartinTheDragon** [comment]
Hello!
I don't think your issue correlates with the fact that you built an RBMK nearby. Are you sure the RBMK is causing it? Does it matter whether you increase or decrease the render distance? I wasn't able to reproduce anything in specific.
Other than that, I can confirm rather severe performance penalties with RBMK rendering due to vanilla Minecraft's block entity rendering, which uploads vertex data every frame. I am planning on implementing GPU instancing to fix that.

**Comment by MartinTheDragon** [comment]
Stale
