### ISSUE TITLE
Make nuke sound somewhat realistic

### ISSUE THREAD

**Issue by ghost** [MartinTheDragon/Nuclear-Tech-Mod-Remake#60]
Minecraft mods have never gotten nuke sounds right
Nukes dont sound like a thunder storm in real life. https://www.youtube.com/watch?v=Mn7PeI2UyEM
The screen shake should also last as long as it does in the video, more intensly the closer you are
It would also be cool is players hear the explosion louder the closer they are, being earraped right next to it

**Comment by SoB1nary** [comment]
>realism
please go away

**Comment by MartinTheDragon** [comment]
Hi!

1. I'm not quite sure if a single pop sound makes that much sense, since calculating a nuclear explosion's crater is a computationally expensive task that takes a bit of time. So you'd either hear the pop, then have to wait a few seconds until the crater suddenly appears, or you'd detonate the nuke with nothing happening, and then the crater "pops in".
2. The camera shake being more intense the closer you are is already a thing. It even consists of two waves, one for the shock-wave that travels through the ground, and another for the one that travels through the air, both delayed depending on your distance (the sound is also delayed). And I'd argue it lasting as long as the sound also makes sense.
3. I can't make explosions louder, the sound engine only allows a max volume of 1.0, with higher values just resulting in a higher range. It would also just overdrive the audio...

So unless we can calculate craters instantly at some point, or we simply find a better SFX loop, let's stick with what we currently have.

**Comment by JulekJulas** [comment]
Well I was thinking that the bomb could precalculate the explosion and when it explodes it doesnt have to calculate anything so it will be stupidly fast, what happens when a block gets placed or removed after it calculated it? I think you could just recalculate a ray in that particular direction. Also I think by playing like 50 sounds at once will result in an earrape.

**Comment by 70000hp** [comment]
That would make every crater exactly the same

**Comment by 70000hp** [comment]
Plus there is a limit as to how fast a nuke can be made before its silly

**Comment by JulekJulas** [comment]
I ment to precalculate the explosion when the nuke is placed so it saves how the crater will look like before it even explodes

**Comment by 70000hp** [comment]
That idea is even worse what?
1. Most people use missiles or mini nukes instead of actually placing a nuke.
2.  Someone could spam the empty nuke shell and completly lag a server due to calculations.
3. This system would be very limited and only useful in one use case

**Comment by JulekJulas** [comment]
The missile can precalculate as it flies and finish on the ground making it faster, and there will be limit of 1 precalculation per player per like few hours. Still it would be nice to see an explosion happen instantly

**Comment by 70000hp** [comment]
Missiles can be shot down, meaning it would do all that calculation for nothing, plus what happens if there are changes in the terrain after the calculation is already done?

**Comment by MartinTheDragon** [comment]
I would've argued the same things 70k said, trying to calculate anything beforehand is a lost cause in sandbox games like Minecraft. However, such a strategy does work in scripted story RPGs, for example the intro sequence in Portal 2, where the entire animation is pre-baked.
