### ISSUE TITLE
Radiation behavior with new versions

### ISSUE THREAD

**Issue by OlorinIV** [MartinTheDragon/Nuclear-Tech-Mod-Remake#7]
**Describe the bug**
Radiation should be able to destroy/kill new plants, like moss blocks, dripleaf, coral, seaweed, cave vines, etc.
Bamboo always leave loads of drops after ground turns to dead grass, possibly affecting gameplay.

Maybe a custom list of block transformation/destruction that could be affected by ntm radiation could be added to config.

**Comment by MartinTheDragon** [comment]
Hello there,
[I am aware](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/blob/6d54d7ed1f1289ce87ae78e15987c35575ba5a10/src/main/kotlin/at/martinthedragon/nucleartech/entities/FalloutRain.kt#L97) of these things and TODOs have been sitting around in the code for a while now. I haven't gotten around to fixing them because I want to make it all in one go when adding support for custom transformations [(also a TODO)](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/blob/6d54d7ed1f1289ce87ae78e15987c35575ba5a10/src/main/kotlin/at/martinthedragon/nucleartech/entities/FalloutRain.kt#L69), like you suggested.

Still, thanks for taking your time and reporting it!

About the custom transformations: I am unsure on whether the configuration for that should be in a config file, or if I should make somewhat of an own format for it and put it in a separate file in the config folder. Got an opinion on that? Anyhow, this is definitely a planned feature.
