### ISSUE TITLE
Game crashes when expoding a nuclear bomb

### ISSUE THREAD

**Issue by FatSassin** [MartinTheDragon/Nuclear-Tech-Mod-Remake#9]
Version 1.18.2 newest release
Mods: Optifine, Biomes you'll go, macaw fences, bridges, Roofs etc, Young's better dungeons, strongholds, mineshafts, JEI newest version beta

When trying to detonate a nuke (either fat Man or the little boy) the game freezes and crashes

**Comment by MartinTheDragon** [comment]
Hello! There's an issue with OptiFine and the baking of the mushroom cloud model. For now, simply remove OptiFine.

Thank you for reporting!

**Comment by FatSassin** [comment]
Thanks 👍

**Comment by MartinTheDragon** [comment]
It's neither fixed, nor have I considered if I'll fix it.
Please leave it open.

**Comment by MartinTheDragon** [comment]
OptiFine compatibility will not happen for the planned future. Everything runs fine with other optimization mods like [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium), and OptiFine can be almost entirely replaced with [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) (although most shaders mess up the mushroom cloud anyway). Attempts at making OptiFine work with NTM have failed, and since I'd also like to mess with graphics and model baking in perhaps weird ways, I won't restrain myself for compatibility with OptiFine (at least for now).
